config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :task  #, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  # post 'users', to: 'users#create'
  get 'login', to: 'session#new'
  post 'login', to: 'session#create'
  delete 'logout', to: 'session#destroy'
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, length: {minimum:3, maximum:20}
    validates_uniqueness_of :name
end

app/models/task.rb
class Task < ApplicationRecord

    belongs_to :user

    validates :task, presence: true, length: {minimum:4, maximum:20}
    validates :comments, presence: true, length: {minimum:4, maximum:1000}
end

app/models/user.rb
class User < ApplicationRecord

    before_save { self.email = email.downcase }
    has_many :tasks, dependent: :destroy
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

    validates :username, presence: true,
        length: {minimum: 3, maximum: 50},
        uniqueness: {case_sensitive: false}
    validates :email, presence: true,
        length: {maximum: 150}, 
        uniqueness: {case_sensitive: false},
        format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:alert] = "You are not logged in!"
            redirect_to login_path
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to '/task' if logged_in?
    end

    def about
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
    
    def new

    end

    def create
        # email = params[:session][:email].downcase
        # password = params[:session][:password]
        user = User.find_by(email:params[:session][:email].downcase)
        # byebug
        if (user && user.authenticate(params[:session][:password]))
            session[:user_id] = user.id
            flash[:notice]= "Login in successful"
            redirect_to user_path(user.id)
        else
            flash.now[:alert]= "Login incredentials wrong" 
            # flash works on a one whole refresh of a webpage. So, using flash in 
            # re_direct without the .now will work, where as on rendering the page
            # the page refresh does not take place
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice]= "Logged Out!"
        redirect_to root_path
    end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController

    #takes place for all the following "only" methods. it gets executed before any action takes place
    before_action :set_task, only: [:show, :edit, :update, :destroy]
    #the require_user method runs first to check if the user is logged in or not. 
    #only if he is logged in, will he be able to go to any definitions.
    before_action :require_user 
    before_action :check_if_same_user, only: [:edit, :update, :destory]

    #redirects to show.html.erb
    # route: /task/:id --> Get method
    def show
        # byebug
        # @task = Task.find(params[:id]) 
    end

    #redirects to index.html.erb
    # route: /task --> Get method
    def index 
        user = current_user
        @tasks = user.tasks.paginate(page: params[:page], per_page: 3)
        # @tasks = Task.all
    end

    #redirects to new.html.erb
    # route: /task/new --> Get method
    def new
        # @task = Task.new #This can also be done to avoid empty values in the new file.
    end

    #redirects from new.html.erb
    # route: /task --> Post method
    def create
        @task = Task.new(task_params)
        user = current_user
        # @task.user_id = User.first.id #a hardcode way of referencing
        @task.user_id = User.find_by(id:user).id
        if @task.save
            flash[:notice]= "Article created successfully" #Appears only when the task is created.
            redirect_to task_path(@task)    
        else
            render 'new'
        end
    end

    #redirects to edit.html.erb
    # route: /task/:id/edit --> Get method
    def edit 
        # @task = Task.find(params[:id]) #This can also be done to avoid empty values in the new file.
    end

    #redirects from edit.html.erb
    # route: /task/:id/edit --> Patch/post method
    def update
        # @task = Task.find(params[:id])

        @task.update(task_params)

        if @task.save
            flash[:notice]= "Article updated successfully" #Appears only when the task is created.
            redirect_to task_path(@task)    
        else
            render 'edit'
        end
    end

    #redirects to none.  it is a destroy method
    # route: /task/:id --> destroy method
    def destroy
        # @task = Task.find(params[:id])
        @task.destroy
        redirect_to '/task'
    end
    
    #methods below this private are accessible only in this file.
    private

    #sets @task with the task selected and of that id in params
    def set_task
        @task = Task.find(params[:id])
    end

    def task_params
        params.require(:task).permit(:task, :comments)
    end

    def check_if_same_user
        if current_user.id != @task.user_id && !current_user.admin?
            flash[:alert] = "Cannot edit that task. You have no access to edit that task"
            redirect_to "/task"
        end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user 
    before_action :check_if_same_user, only: [:edit, :update, :destory]

    def new
        @user = User.new
    end

    def index 
        # @users = User.all
        @users = User.paginate(page: params[:page], per_page: 2)
    end

    def show
        @tasks = @user.tasks.paginate(page: params[:page], per_page: 3)
    end

    def create
        # byebug
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "Welcome, #{@user.username}"
            redirect_to user_path(@user.id)
        else
            render 'new'
        end
    end

    def edit
    end

    def update

        @user.update(user_params)

        if @user.save
            flash[:notice]= "User Data updated successfully" #Appears only when the user is created.
            redirect_to '/task'
        else
            render 'edit'
        end
    end

    def destroy
        @user.destroy
        session[:user_id] = nil if @user == current_user
        flash[:notice] == "Account and all tasks associated removed"
        redirect_to root_path
    end

    private

    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def check_if_same_user
        if current_user.id != @user.id && !current_user.admin?
            flash[:alert] = "Not the same user."
            redirect_to "/task"
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

    
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navigation_bar.html.erb
<nav class="navbar navbar-expand-sm bg-light">
    <ul class="navbar-nav">
        <li class="nav-item btn-nav">
            <%= link_to  "Home", root_path, class:"nav-link" %>
        </li>

        <% if logged_in? %>
        <li class="nav-item btn-nav">
            <div class="dropdown">
                <span class="tasks-dd nav-link dropdown-toggle" data-toggle="dropdown">Tasks</span>
                <ul class="dropdown-menu dd-shadow">
                    <li>
                        <%= link_to  "Show All Tasks", task_index_path, class:"nav-link" %>
                    </li>
                    <li>
                        <%= link_to  "Create A Task", new_task_path, class:"nav-link" %>
                    </li>
                </ul>
            </div>

        </li>

        <li class="nav-item btn-nav">
            <div class="dropdown">
                <span 
                    class="tasks-dd nav-link dropdown-toggle" 
                    data-toggle="dropdown">
                    Profile <%= "(Admin)" if current_user.admin? %>
                </span>
                <ul class="dropdown-menu dd-shadow">
                    <li class="nav-item">
                        <%= link_to  current_user.username, user_path(current_user), class:"nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to  "Users Present", users_path, class:"nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to  "Log Out", 
                            logout_path, 
                            class:"nav-link", 
                            method: :delete, 
                            data: { confirm: 'Are you sure you want to Logout?' } 
                        %>
                    </li>
                    <li class="nav-item">
                        <%= link_to  "Delete My Account", 
                            user_path(current_user), 
                            class:"nav-link text-danger", 
                            method: :delete, 
                            data:{ 
                                confirm:"Are you sure you want to delete your account? 
                                All the data will be lost" 
                            } 
                        %>
                    </li>
                </ul>
            </div>
        </li>
        <% else %>
        <li class="nav-item btn-nav">
            <%= link_to  "Login", login_path, class:"nav-link" %>
        </li>
        <li class="nav-item btn-nav">
            <%= link_to  "Signup", signup_path, class:"nav-link" %>
        </li>
        <% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="font-common">
    <%= render 'layouts/navigation_bar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
    <h1 class="header-index">About</h1>

app/views/pages/home.html.erb
<h1 class="header-index">Welcome to the Homepage</h1>

<% flash.each do |name, msg| %>
    <p class="flash-message">
        <%= msg %>
    </p>
<% end %>

app/views/session/new.html.erb
<h1 class="header-index">Login</h1>
<% flash.each do |name, msg| %>
    <p class="flash-message">
        <%= msg %>
    </p>
<% end %>
<div class="form">
    <%= form_with(scope: :session, url: login_path, local: true, class:"my-form") do |f| %>

    <p>
        <%= f.label :email, class:"label" %>
        <%= f.email_field :email, class:"field", placeholder:"Enter your Email" %>
    </p>

    <p>
        <%= f.label :password, class:"label" %>
        <%= f.password_field :password, class:"field", placeholder:"Enter your Password" %>
    </p>
    <%= f.submit "Login", disable_with: 'Loging In...', class:"btn-this-app" %>

    <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if obj && obj.errors.any?  %>
<div class="error-messages">
    <p>Check below for the following errors!!</p>
    <ul>
        <% obj.errors.full_messages.each do |error| %>
        <li><%= error %></li>
        <% end %>
    </ul>
</div>
<% end %>

app/views/shared/_tasks_table.html.erb
<% if @tasks.exists? %>
<%= will_paginate @tasks %>
<table class="index-table">
    <thead>
        <tr>
            <th class="table-head-row task border">Task</th>
            <th class="table-head-row comments border">Comments</th>
            <th class="table-head-row creator border">Created By</th>
            <th class="table-head-row created-updated border">Created On</th>
            <th class="table-head-row created-updated border">Last Update On</th>
            <th class="table-head-row actions border" colspan="3">Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @tasks.each do |task| %>
        <tr class="table-content-row">
            <td class="table-data-row border"> <%= task.task %> </td>
            <td class="table-data-row border"> <%= task.comments %> </td>
            <td class="table-data-row border"> <%= task.user.username %> </td>
            <td class="table-data-row border">
                <%= task.created_at.day %> -
                <%= task.created_at.month %> -
                <%= task.created_at.year %>
            </td>
            <td class="table-data-row border">
                <%= task.updated_at.day %> -
                <%= task.updated_at.month %> -
                <%= task.updated_at.year %>
            </td>
            <% if task.user_id == current_user.id || current_user.admin? %>
                <td class="table-data-row border"> 
                    <%= link_to  "Delete", 
                        task_path(task.id), 
                        method: :delete, 
                        data: { confirm: 'Are you sure?' } 
                    %> 
                </td>
                <td class="table-data-row border"> 
                    <%= link_to  "Edit", edit_task_path(task.id) %> 
                </td>
            <% else %>
                <td class="table-data-row border"> 
                    Delete
                </td>
                <td class="table-data-row border"> 
                    Edit
                </td>
            <% end %>
            
            <td class="table-data-row border"> <%= link_to  "Show", task_path(task.id) %> </td>
            
        </tr>
        <% end %>
    </tbody>
</table>
<%= will_paginate @tasks %>
<% else %>
<h5 class="header-index">
    No Tasks available for this user.
    <%= link_to  "Create a Task", new_task_path %>
</h5>
<% end %>

app/views/task/_error_messages.html.erb
<% if @task && @task.errors.any?  %>
<div class="error-messages">
    <p>Check below for the following errors!!</p>
    <ul>
        <% @task.errors.full_messages.each do |error| %>
        <li><%= error %></li>
        <% end %>
    </ul>
</div>
<% end %>

app/views/task/edit.html.erb
<h1 class="header-index">Edit Task</h1>

<%= render 'shared/error_messages', obj:@task %>
<div class="form">
    <%= form_with(model: @task, local: true) do |f| %>
    <p>
        <%= f.label :task, class:"label" %>
        <%= f.text_field :task, class:"field" %>
    </p>

    <p>
        <%= f.label :comments, class:"label" %>
        <%= f.text_area :comments, class:"field" %>
    </p>
    <%= f.submit "Update Task", disable_with: 'Updating...', class:"btn-this-app" %>

    <% end %>
</div>

<hr>

<div class="my-link">
    <%= link_to  "Go Back", task_index_path, class:"btn-this-app" %> 
</div>

app/views/task/index.html.erb
<h1 class="header-index">My Tasks</h1>

<% flash.each do |name, msg| %>
<p class="flash-message">
    <%= msg %>
</p>
<% end %>

<%= render 'shared/tasks_table' %>
<hr>
<div class="my-link">
    <%= link_to  "Create a new Task", new_task_path, class:"btn-this-app" %>
</div>

app/views/task/new.html.erb
<h1 class="header-index">Create a new Task</h1>

<%= render 'shared/error_messages', obj:@task %>
<div class="form">
    <%= form_with scope: :task, url: '/task', local: true, class:"my-form" do |f| %>
    <p>
        <%= f.label :task, class:"label" %>
        <%= f.text_field :task, class:"field" %>
    </p>

    <p>
        <%= f.label :comments, class:"label" %>
        <%= f.text_area :comments, class:"field" %>
    </p>
    <%= f.submit "Create Task", disable_with: 'Creating...', class:"btn-this-app" %>

    <% end %>
</div>

<hr>

<div class="my-link">
    <%= link_to  "Go Back", task_index_path, class:"btn-this-app" %> 
</div>

app/views/task/show.html.erb
<div class="show-tasks">
    <% flash.each do |name, msg| %>
    <p class="flash-message">
        <%= msg %>
    </p>
    <% end %>

    <h1 class="header-index">Your Task</h1>

    <div class="task-comments">
        <p>
            <span class="head">Task:</span> 
            <span class="content"><%= @task.task %></span>
        </p>
        <p>
            <span class="head">Comments:</span> 
            <span class="content"><%= @task.comments %></span>
        </p>
        <p>
            <span class="head">Created By:</span> 
            <span class="content"><%= @task.user.username %></span>
        </p>
        <p>
            <span class="head">Created On:</span> 
            <span class="content">
                <%= @task.created_at.day %> -
                <%= @task.created_at.month %> -
                <%= @task.created_at.year %>
            </span>
        </p>
        <p>
            <span class="head">Last Updated on:</span> 
            <span class="content">
                <%= @task.updated_at.day %> -
                <%= @task.updated_at.month %> -
                <%= @task.updated_at.year %>
            </span>
        </p>
    </div>

    <p class="quick-links">
        <% if @task.user_id == current_user.id || current_user.admin? %>
            <%= link_to  "Edit", edit_task_path(@task.id), class:"edit" %> |
            <%= link_to  "Delete", task_path(@task.id), method: :delete, data: { confirm: 'Are you sure?' }, class:"delete" %> |
        <% end %>
        
        <%= link_to  "Go Back", task_index_path,class:"back" %>
    </p>
</div>

app/views/users/edit.html.erb
<h1 class="header-index">Edit User Details</h1>

<%= render 'shared/error_messages', obj:@user %>
<div class="form">
    <%= form_with(model: @user, local: true) do |f| %>
    <p>
        <%= f.label :username, class:"label" %>
        <%= f.text_field :username, class:"field" %>
    </p>

    <p>
        <%= f.label :email, class:"label" %>
        <%= f.email_field :email, class:"field" %>
    </p>

    <p>
        <%= f.label :password, class:"label" %>
        <%= f.password_field :password, class:"field" %>
    </p>
    <%= f.submit "Update User", disable_with: 'Updating...', class:"btn-this-app" %>

    <% end %>
</div>

app/views/users/index.html.erb
<% flash.each do |name, msg| %>
    <p class="flash-message">
        <%= msg %>
    </p>
<% end %>
<%= will_paginate @users %>
<table class="index-table">
    <thead>
        <tr>
            <th class="table-head-row task border">User</th>
            <th class="table-head-row comments border">Email</th>
            <th class="table-head-row creator border">No.of Tasks</th>
            <th class="table-head-row actions border" colspan="2">Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
        <tr class="table-content-row">
            <% if user == current_user || current_user.admin? %>
                <td class="table-data-row border"> 
                    <%= link_to user.username , user_path(user.id) %>
                </td>
            <% else %>
                <td class="table-data-row border"> <%= user.username %> </td>
            <% end %>
            <td class="table-data-row border"> <%= user.email %> </td>
            <td class="table-data-row border"> <%= user.tasks.length %> </td>
            <td class="table-data-row border"> 
                <%= link_to  "View Profile", user_path(user.id) %> 
            </td>
            <% if user == current_user || current_user.admin? %>
                <td class="table-data-row border"> 
                    <%= link_to  "Edit Profile", edit_user_path(user.id) %>
                </td>
            <% else %>
                <td class="table-data-row border"> Edit Profile </td>
            <% end %>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/users/new.html.erb
<h1 class="header-index">Signup Users</h1>

<%= render 'shared/error_messages', obj:@user %>
<div class="form">
    <%= form_with scope: :user, url: '/users', local: true, class:"my-form" do |f| %>
    <p>
        <%= f.label :username, class:"label" %>
        <%= f.text_field :username, class:"field" %>
    </p>

    <p>
        <%= f.label :email, class:"label" %>
        <%= f.email_field :email, class:"field" %>
    </p>

    <p>
        <%= f.label :password, class:"label" %>
        <%= f.password_field :password, class:"field" %>
    </p>
    <%= f.submit "Create User", disable_with: 'Creating...', class:"btn-this-app" %>

    <% end %>
</div>

app/views/users/show.html.erb
<div class="show-tasks">
    <% flash.each do |name, msg| %>
    <p class="flash-message">
        <%= msg %>
    </p>
    <% end %>

    <h1 class="header-index"><%= @user.username %>'s profile</h1>

    <div class="task-comments">
        <p>
            <span class="head">User name:</span> 
            <span class="content"><%= @user.username %></span>
        </p>
        <p>
            <span class="head">Email ID:</span> 
            <span class="content"><%= @user.email %></span>
        </p>
        <p>
            <span class="head">Account Created On:</span> 
            <span class="content">
                <%= @user.created_at.day %> -
                <%= @user.created_at.month %> -
                <%= @user.created_at.year %>
            </span>
        </p>
    </div>

    <%= render 'shared/tasks_table' %>

    <p class="quick-links">
        <% if @user.id == current_user.id || current_user.admin? %>
            <%= link_to  "Edit Me", edit_user_path(@user.id), class:"edit" %> |
        <% end %>
        <% if @user.id == current_user.id || current_user.admin? %>
            <%= link_to  "Delete Me", 
                user_path(@user.id), 
                class:"delete", 
                method: :delete, 
                data: { confirm: 'Are you sure you want to delete this account?' }
            %> |
        <% end %>
        <%= link_to  "Go Back", '/task', class:"back" %>
    </p>
</div>